version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  name: builds/$CODEBUILD_BUILD_NUMBER/artifacts
  base-directory: build
  files:
    - '**/*'
